version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "arfshl"
    groups:
      github-actions-updates:
        patterns:
          - "*"

  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "arfshl"
    groups:
      gems-updates:
        patterns:
          - "*"