# This script is licensed under GPLv3

require "erb"
require "uri"

puts "Generating README..."

# Define file locations.
# - rawdata.txt: input generated by the downloader
# - template: ERB template used to build the README
# - output: final generated README
RAWDATA_FILE  = File.join(__dir__, "rawdata.txt")
TEMPLATE_FILE = File.expand_path("../../templates/chrome-offline-installers.erb", __dir__)
OUTPUT_FILE   = File.expand_path("../../chrome-offline-installers/README.md", __dir__)

# Read the raw input data.
input = File.read(RAWDATA_FILE)

# Split the input into individual blocks.
# Each block starts with "Version:" and ends before the next
# "Version:" line or the end of the file.
blocks = input.scan(/Version:.*?(?=^Version:|\z)/m)

# Metadata describing each parsed block.
# The array order must match the order of blocks in rawdata.txt.
titles = [
  {
    title: "Chrome (64-bit) for Windows latest",
    arch: "64-bit"
  },
  {
    title: "Chrome (32-bit) for Windows 10",
    arch: "32-bit"
  },
  {
    title: "Chrome (64-bit) for Windows 7/8/8.1",
    arch: "64-bit"
  },
  {
    title: "Chrome (32-bit) for Windows 7/8/8.1",
    arch: "32-bit"
  },
  {
    title: "Chrome (32-bit) for Windows XP/Vista",
    arch: "32-bit"
  },
  {
    title: "Chrome (64-bit) for macOS latest",
    arch: "64-bit"
  }
]

# Extract the value associated with a specific key from a block.
# Example:
#   Version: 138.0.7204.169
# Returns:
#   "138.0.7204.169"
def value(text, key)
  text[/^#{key}:\s*(.+)$/, 1]&.strip
end

# Convert a file size in bytes to megabytes
# and format it with two decimal places.
def size_mb(bytes)
  "%.2f MB" % (bytes.to_i / 1024.0 / 1024.0)
end

# Generate alternative official download URLs.
# The original URL is preserved, then equivalent
# Google mirror URLs are generated using the same path.
def alt_links(url)
  uri = URI(url)
  path = uri.path

  [
    url,
    "https://dl.google.com#{path}",
    "https://edgedl.me.gvt1.com/edgedl#{path}"
  ]
end

# Load the ERB template.
template = ERB.new(File.read(TEMPLATE_FILE), trim_mode: "-")

# Render the template using all variables and helper methods
# available in the current binding.
readme = template.result(binding)

# Write the rendered content to the output README file.
File.write(OUTPUT_FILE, readme)

# Notify that generation completed successfully.
puts "README has been successfully generated"